services:

  frontend:
    container_name: frontend
    build:
      context: ./web
      target: prod
      args:
        - VITE_BACKEND_URL=http://www.quickdev.com/api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Fichier de config NGINX
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - quickdev_app_network

  backend:
    container_name: backend
    user: "${UID}:${GID}"
    build:
      context: ./backend
    env_file:
      - ./backend/.env.prod
    volumes:
      - "/tmp/quickdev:/app/projects"
    ports:
      - "3333:3333"
    depends_on:
      - postgres_db_app
    networks:
      - "quickdev_app_network"

  postgres_db_app:
    image: postgres:17
    container_name: postgres_db_app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quickdev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - "quickdev_app_network"

volumes:
  postgres_data:


networks:
  quickdev_app_network:


